# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-23 01:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgnization', '0002_auto_20170421_1238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='image',
            field=models.ImageField(default='', upload_to='teacher/%Y/%m', verbose_name='\u8bb2\u5e08\u5934\u50cf'),
        ),
    ]
